
auth.token=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

defaults.org=safety-pin
defaults.project=react-native

defaults.url=https://sentry.io/
