name: Run, Build, and Publish Expo App

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build:
    name: Build APK
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      - name: Build APK
        run: npx eas-cli build -p android --non-interactive --profile preview

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: dist/*.apk

  publish:
    name: Publish APK to Public Repository
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v4
        with:
          repository: your-user/public-releases
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: Create GitHub Release in Public Repo
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          body: "🚀 New APK Release from Private Repo!"
          files: "*.apk"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
